diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'), # http://127.0.0.1:8000/diary/
    path('add/',views.AddView.as_view(), name='add'), # http://127.0.0.1:8000/diary/add/
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'), # http://127.0.0.1:8000/diary/update/#
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'), # http://127.0.0.1:8000/diary/delete/#
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'), # http://127.0.0.1:8000/diary/detail/#
]

first/urls.py
from django.contrib import admin
from django.urls import path,include  # 変更

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/',include('diary.urls')),  # 追加
]

diary/models.py
from django.db import models
from django.utils import timezone

app_name = 'diary'

class Day(models.Model):
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'

diary/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .forms import DayCreateForm
from .models import Day
from django.contrib.auth.mixins import LoginRequiredMixin 

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'diary/day_list.html'
    model = Day

class AddView(LoginRequiredMixin, generic.CreateView): # 修正
 # class AddView(generic.CreateView):
    template_name = 'diary/day_form.html'
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class UpdateView(LoginRequiredMixin, generic.UpdateView):  # 修正
 # class UpdateView(generic.UpdateView):
    template_name = 'diary/day_form.html'
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class DeleteView(LoginRequiredMixin, generic.DeleteView):  # 修正
 # class DeleteView(generic.DeleteView):
    template_name = 'diary/day_confirm_delete.html'
    model = Day
    success_url = reverse_lazy('diary:index')

class DetailView(generic.DetailView):
    template_name = 'diary/day_detail.html'
    model = Day

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>日記アプリケーション</title>
  </head>
  <body>
    <div class="container">
        <nav class="nav">
            <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
            {% if user.is_superuser %}
              <a class="nav-link" href="{% url 'diary:add' %}" target="_blank">追加</a>
            {% endif %}
        </nav>
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text }}</td>
        </tr>
    </table>
    <p>データを削除します。</p>
    <button type="submit" class="btn btn-primary">削除</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_details.html
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
    <tr>
        <th>日付</th>
        <td>{{ day.date }}</td>
    </tr>
    <tr>
        <th>タイトル</th>
        <td>{{ day.title }}</td>
    </tr>
    <tr>
        <th>本文</th>
        <td>{{ day.text | linebreaksbr | urlize }}</td>
    </tr>
</table>
{% endblock %}

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</td>
            <td>{{ day.date }}</td>
            <td>
                {% if user.is_superuser %}
                    <a href="{% url 'diary:update' day.pk %}" target="_blank">更新</a>
                {% endif %}
            </td>
            <td>
                {% if user.is_superuser %}
                    <a href="{% url 'diary:delete' day.pk %}" target="_blank">削除</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}